### ISSUE TITLE
is it possible to use this tool from CLI/ programmatically (without GUI)

### ISSUE THREAD

**Issue by mbassiouny33** [0xb160c0c5/FontLoaderEx#1]
Hi there,

Thanks a lot for this great tool!

I would like to ask if there is a way to use it from CLI/ programmatically, without having to open the GUI.

I see no documentation at all on such feature.

Thanks :)

**Comment by 0xb160c0c5** [comment]
You can't, but there is a workaround:
Create a batch file named ``FontLoaderExCLI.bat`` in the same folder as FontLoaderEx with the following content:
```batch
@start /d . /min FontLoaderEx %*
```
Then you can use the syntax ``FontLoaderExCLI <font1> <font2> ...`` or ``FontLoaderExCLI <fontfolder>`` to launch FontLoaderEx from CLI and load fonts wth the window minimized.

**Comment by mbassiouny33** [comment]
Thanks for the workaround!
